@startuml Login Admin

actor Client

participant AuthController
participant ModelDto
participant RequestValidation
participant AuthService
participant Jsonwebtoken
participant UserModel
participant CookieUtil

database MongoDB

' Step 1
    activate Client
    Client -> AuthController: POST /api/auth/login-admin
    activate AuthController

break
break


' Step 2
group Validation Flow
    AuthController -> RequestValidation: validateSchema(LoginDto)
   activate RequestValidation
    alt validation error
        RequestValidation --x RequestValidation: throw HttpException(400)
        RequestValidation --x AuthController: throw HttpException(400)
        AuthController -->> Client: HTTP 400 Bad Request
    end
    RequestValidation -->> AuthController: return valid data
    deactivate RequestValidation
    
end

break
break


' step 3
group Business Logic Flow
    AuthController -> AuthService: authenticateUserService(email, password)
    activate AuthService
    AuthService -> UserModel: findOne()
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt query fail 
        MongoDB --x UserModel: throw error
        UserModel --x AuthService: throw error
        AuthService --x AuthController: throw error
        AuthController -->> Client: HTTP 500 Internal Server Error
    else email not found
        MongoDB -->> UserModel: return null
        UserModel -->> AuthService: return null
        AuthService -->> AuthController: return null
        AuthController --x AuthController: throw(HttpException(400))
        AuthController -->> Client: HTTP 400 Bad Request
    else password not match
        MongoDB -->> UserModel: return user
        UserModel -->> AuthService: return user
        AuthService -->> AuthController: return user
        AuthController --x AuthController: throw(HttpException(400))
        AuthController -->> Client: HTTP 400 Bad Request
    end

    MongoDB -->> UserModel: return user
    deactivate MongoDB
    UserModel -->> AuthService: return user
    deactivate UserModel
    AuthService -->> AuthController: return user
    deactivate AuthService
    AuthController -> AuthService: generateTokensService()
    activate AuthService
    AuthService -> Jsonwebtoken: sign(payload, secret, options)
    activate Jsonwebtoken
    Jsonwebtoken -->> AuthService: return accessToken
    deactivate Jsonwebtoken
    AuthService -> Jsonwebtoken: sign(payload, secret, options)
    activate Jsonwebtoken
    Jsonwebtoken -->> AuthService: return refreshToken
    deactivate Jsonwebtoken
    AuthService -> UserModel: updateOne()
    activate UserModel
    UserModel -> MongoDB: query update
    activate MongoDB

    alt update fail
        MongoDB --x UserModel: throw error
        UserModel --x AuthService: throw error
        AuthService --x AuthController: throw error
        AuthController -->> Client: HTTP 500 Internal Server Error
    end

    MongoDB -->> UserModel: return accessToken, refreshToken
    deactivate MongoDB
    UserModel -->> AuthService: return accessToken, refreshToken
    deactivate UserModel
    AuthService -->> AuthController: return accessToken, refreshToken
    deactivate AuthService
    AuthController -> CookieUtil: setSession(accessToken, refreshToken)
    activate CookieUtil
    CookieUtil -->> AuthController: return cookie
    deactivate CookieUtil


    
end   
break 
break

group Transform data response
    AuthController -> ModelDto: new(UserDto)
    activate ModelDto
    ModelDto -->> AuthController: return UserDto 
    deactivate ModelDto
AuthController --> Client: HTTP 200 Success
deactivate AuthController
end


@enduml