@startuml Create Order

actor Client

box "Application Layer"
participant OrdersRouter 
participant ErrorMiddleware 
participant AsyncHandler 
end box

box "Authentication"
participant JwtAuthMiddleware 
participant CookieUtil
participant AuthService
participant jsonwebtoken
end box

box "Authorization"
participant UserService 
participant UserModel
end box

box "Validation"
participant RequestValidation
end box

box "Business Logic"
participant OrdersController
participant ModelDto
participant ApiResponse
participant OrdersWorker
participant UsersService
participant GhnService
participant OrdersService
participant GeoapifyService
participant GhnAPI
participant OrderModel
participant RoleModel
end box

database MongoDB

' Step 1
group Request Initialization
    Client -> OrdersRouter: POST /api/orders/create-orders
    activate Client
    activate OrdersRouter
    OrdersRouter -> AsyncHandler: asyncHandler(createOrderController)
    activate AsyncHandler
end

break
break

' Step 2
group Authentication Flow
    AsyncHandler -> JwtAuthMiddleware: isAuthorizedAndHasPermission
    activate JwtAuthMiddleware

    JwtAuthMiddleware -> JwtAuthMiddleware: extract token
    alt token not provided
        JwtAuthMiddleware -> CookieUtil: clearSession(res)
        activate CookieUtil
        CookieUtil -->> JwtAuthMiddleware: return void
        deactivate CookieUtil
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end 

    JwtAuthMiddleware -> AuthService: verifyTokenService(token)
    activate AuthService
    AuthService -> jsonwebtoken: verify(token, SECRET)
    activate jsonwebtoken
    alt token invalid
        jsonwebtoken --x AuthService: throw Error
        AuthService -->> JwtAuthMiddleware: catch Error and return null
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end

    jsonwebtoken -->> AuthService: return data decoded
    deactivate jsonwebtoken
    AuthService -->> JwtAuthMiddleware: return data decoded
    deactivate AuthService
    JwtAuthMiddleware -> UserService: getUserByIdService(decoded.id)
    activate UserService
    UserService -> UserModel: findOne(filters)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt user not found
        MongoDB -->> UserModel: return null
        UserModel -->> UserService: return null
        UserService -->> JwtAuthMiddleware: return null
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return user
    deactivate MongoDB
    UserModel -->> UserService: return user
    deactivate UserModel
    UserService -->> JwtAuthMiddleware: return user
    deactivate UserService

    alt unverified account
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(403))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 403 Forbidden
        deactivate ErrorMiddleware
    end
end

break
break

' Step 3
group Authorization Flow
    JwtAuthMiddleware -> UserService: checkUserHasPermissionService(userId, method, endpoint)
    activate UserService
    UserService -> UserModel: findById(id).populate(role).populate(permissions)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt User doesn't have permissions 
        MongoDB -->> UserModel: return empty permissions
        UserModel -->> UserService: return empty permissions
        UserService -->> JwtAuthMiddleware: return false
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 403 Forbidden
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return permissions
    deactivate MongoDB
    UserModel -->> UserService: return permissions
    deactivate UserModel
    UserService -->> JwtAuthMiddleware: return true
    deactivate UserService
end

break
break

' Step 4
group Validation Flow
    JwtAuthMiddleware -> RequestValidation: validateSchema(createOrderDto)
    deactivate JwtAuthMiddleware
    activate RequestValidation
    
    alt validation error
        RequestValidation ->> RequestValidation: next(HttpException(400))
        RequestValidation ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 400 Bad Request
        deactivate ErrorMiddleware
    end
end

break
break

' Step 5
group Business Logic Flow
    RequestValidation -> OrdersController: createOrderController
    deactivate RequestValidation
    activate OrdersController
    OrdersController -> UsersService: getUserByIdService(customerId)
    activate UsersService

    alt customerId not provided
        UsersService -->> OrdersController: return null
        OrdersController --x OrdersController: throw(HttpException(400))
        OrdersController --x AsyncHandler: catch HttpException and next(HttpException(400))
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 400 Bad Request
        deactivate ErrorMiddleware
    end

    UsersService -> UserModel: findOne(filters)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt select fail 
        MongoDB --x UserModel: throw Error
        UserModel --x UsersService: throw Error
        UsersService --x OrdersController: throw Error
        OrdersController --x AsyncHandler: catch Error and next(Error)
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500 Internal Server Error
        deactivate ErrorMiddleware

    else user not found
        MongoDB -->> UserModel: return null
        UserModel -->> UsersService: return null
        UsersService -->> OrdersController: return null
        OrdersController --x OrdersController: throw(HttpException(404))
        OrdersController --x AsyncHandler: catch HttpException and next(HttpException(404))
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 404 Not Found
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return customer
    deactivate MongoDB
    UserModel -->> UsersService: return customer
    deactivate UserModel
    UsersService -->> OrdersController: return customer
    deactivate UsersService
    OrdersController -> GhnService: getProvinceService(provinceCode)
    activate GhnService
    GhnService -> GhnAPI: GET /master-data/province
    activate GhnAPI

    alt get fail
        GhnAPI -->> GhnService: return null
        GhnService -->> OrdersController: return null
        OrdersController --x OrdersController: throw(HttpException(404))
        OrdersController ->> AsyncHandler: catch HttpException and next(HttpException(404))
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 404 Not Found
        deactivate ErrorMiddleware
    end

    GhnAPI -->> GhnService: return province
    deactivate GhnAPI
    GhnService -->> OrdersController: return province   
    deactivate GhnService
    OrdersController -> GhnService: getDistrictService(districtCode, provinceCode)
    activate GhnService
    GhnService -> GhnAPI: GET /master-data/district
    activate GhnAPI

    alt get fail
        GhnAPI -->> GhnService: return null
        GhnService -->> OrdersController: return null
        OrdersController --x OrdersController: throw(HttpException(404))
        OrdersController ->> AsyncHandler: catch HttpException and next(HttpException(404))
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 404 Not Found
        deactivate ErrorMiddleware
    end

    GhnAPI -->> GhnService: return district
    deactivate GhnAPI
    GhnService -->> OrdersController: return district
    deactivate GhnService
    OrdersController -> GhnService: getWardService(wardCode, districtCode)
    activate GhnService
    GhnService -> GhnAPI: GET /master-data/ward
    activate GhnAPI

    alt get fail
        GhnAPI -->> GhnService: return null
        GhnService -->> OrdersController: return null
        OrdersController --x OrdersController: throw(HttpException(404))
        OrdersController ->> AsyncHandler: catch HttpException and next(HttpException(404))
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 404 Not Found
        deactivate ErrorMiddleware
    end

    GhnAPI -->> GhnService: return ward
    deactivate GhnAPI
    GhnService -->> OrdersController: return ward
    deactivate GhnService
    OrdersController -> GeoapifyService: checkValidAddressService(fullAddress)
    activate GeoapifyService
    
    alt Invalid fullAddress
        GeoapifyService -->> OrdersController: return false
        OrdersController --x OrdersController: throw(HttpException(404))
        OrdersController ->> AsyncHandler: catch HttpException and next(HttpException(404))
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 404 Not Found
        deactivate ErrorMiddleware
    end

    GeoapifyService -->> OrdersController: return true
    deactivate GeoapifyService
    OrdersController -> OrdersWorker: createOrderJob()
    activate OrdersWorker

    alt create fail
        OrdersWorker --x OrdersController: throw Error
        OrdersController --x AsyncHandler: catch Error and next(Error)
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500 Internal Server Error
        deactivate ErrorMiddleware
    end

    OrdersWorker -->> OrdersController: return job
    deactivate OrdersWorker
    

end

break 
break 

group Transform data response
    OrdersController -> OrdersService: getOrderByIdService(id)
    activate OrdersService
    
    alt id not provided
        OrdersService -->> OrdersController: return null
        OrdersController --x OrdersController: throw(HttpException(400))
        OrdersController ->> AsyncHandler: catch HttpException and next(HttpException(400))
        AsyncHandler -->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 400 Bad Request
        deactivate ErrorMiddleware
    end

    OrdersService -> OrderModel: findOne(filters)
    activate OrderModel
    OrderModel -> MongoDB: query select
    activate MongoDB

    alt select fail 
        MongoDB --x OrderModel: throw Error
        OrderModel --x OrdersService: throw Error
        OrdersService --x OrdersController: throw Error
        OrdersController --x AsyncHandler: catch Error and next(Error)
        AsyncHandler -->> ErrorMiddleware: handleError(Error) 
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500 Internal Server Error
        deactivate ErrorMiddleware
    end

    MongoDB -->> OrderModel: return orderDetail
    deactivate MongoDB
    OrderModel -->> OrdersService: return orderDetail
    deactivate OrderModel
    OrdersService -->> OrdersController: return orderDetail
    deactivate OrdersService
    
    OrdersController -> ModelDto: new(OrderDto, orderDetail)
    activate ModelDto
    ModelDto -->> OrdersController: return OrderDto instance
    deactivate ModelDto

    OrdersController -> ApiResponse: success(OrderDto)
    activate ApiResponse
    ApiResponse -->> OrdersController: return ApiResponse instance
    deactivate ApiResponse 
end

OrdersController -->> AsyncHandler: return ApiResponse instance
deactivate OrdersController
AsyncHandler --> Client: HTTP 200 Success
deactivate AsyncHandler
deactivate OrdersRouter

@enduml
