@startuml View list Disctricts

actor Client
participant DivisionsController
participant ModelDto
participant GhnService 
participant GhnAPI

database MongoDB

' Step 1
    activate Client
    Client -> DivisionsController: GET /api/divisions/get-wards-by-district-code/:districtCode
    activate DivisionsController

break
break

' step 2
group Business Logic Flow
    DivisionsController -> GhnService: getWardsByDistrictIdService(districtCode)
    activate GhnService
    GhnService -> GhnAPI: GET /master-data/ward
    activate GhnAPI

    alt get fail
        GhnAPI -->> GhnService: return null
        GhnService -->> DivisionsController: return null
        DivisionsController --x DivisionsController: throw(HttpException(404))
        DivisionsController -->> Client: HTTP 404 Not Found
    end

    GhnAPI -->> GhnService: return ward
    deactivate GhnAPI
    GhnService -->> DivisionsController: return ward
    deactivate GhnService


end
break
break

group Transform data response
    DivisionsController -> ModelDto: newList(WardDto)
    activate ModelDto
    ModelDto -->> DivisionsController: return WardDto 
    deactivate ModelDto
DivisionsController --> Client: HTTP 200 Success
deactivate DivisionsController
end



@enduml