@startuml Forgot Password

actor Client

box "Application Layer"
participant AuthRouter 
participant ErrorMiddleware 
participant AsyncHandler 
end box

box "Validation"
participant RequestValidation
end box

box "Business Logic"
participant AuthController
participant ApiResponse
participant AuthService
participant UsersService
participant MailerService
participant StringUtil
participant UserOtpModel
participant UserModel
end box

database MongoDB

' Step 1
group Request Initialization
    Client -> AuthRouter: POST /api/auth/forgot-password
    activate Client
    activate AuthRouter
    AuthRouter -> AsyncHandler: asyncHandler(forgotPasswordController)
    activate AsyncHandler
end

break
break


' Step 2
group Validation Flow
    AsyncHandler -> RequestValidation: validateBody(ForgotPasswordDto)
    activate RequestValidation
    alt validation error
        RequestValidation ->> RequestValidation: next(HttpException(400))
        RequestValidation ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 400 Bad Request
        deactivate ErrorMiddleware
    end
    
end

break
break


' step 3
group Business Logic Flow
    RequestValidation -> AuthController: sendOtpViaEmailController
    deactivate RequestValidation
    activate AuthController
    AuthController -> UsersService: getUserByIdService(userId)
    activate UsersService

    alt userId not provided
        UsersService -->> AuthController: return null
        AuthController --x AuthController: throw(HttpException(400))
        AuthController ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 400 Bad Request
        deactivate ErrorMiddleware
    end

    UsersService -> UserModel: findOne(filters)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt select fail 
        MongoDB --x UserModel: throw Error
        UserModel --x UsersService: throw Error
        UsersService --x AuthController: throw Error
        AuthController --x AuthController: throw(HttpException(500))
        AuthController ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500 Internal Server Error
        deactivate ErrorMiddleware

    else user not found
        MongoDB -->> UserModel: return null
        UserModel -->> UsersService: return null
        UsersService -->> AuthController: return null
        AuthController --x AuthController: throw(HttpException(404))
        AuthController ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 404 Not Found
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return user
    deactivate MongoDB
    UserModel -->> UsersService: return user
    deactivate UserModel
    UsersService -->> AuthController: return user
    deactivate UsersService
    AuthController -> AuthService: createResetPasswordTokenService(userId)
    activate AuthService
    AuthService -> Jsonwebtoken: sign(payload, secret, options)
    activate Jsonwebtoken
    Jsonwebtoken -->> AuthService: return token
    deactivate Jsonwebtoken
    AuthService -->> AuthController: return token
    deactivate AuthService
    AuthController -> AuthController: join()
    AuthController -> MailerService: sendResetPasswordRequestService(email, resetURL)
    activate MailerService
    MailerService -> MailerService: getEmailTemplateToString()
    MailerService -> MailerService: sendMail()

    alt send mail fail
        MailerService --x MailerService: throw error
        MailerService --x AuthController: throw error
        AuthController --x AuthController: throw(HttpException(500))
        AuthController ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500 Internal Server Error
        deactivate ErrorMiddleware
    end

    MailerService -->> AuthController: return result
    deactivate MailerService
       
end   
break 
break


AuthController -> ApiResponse: success(null, success message)
activate ApiResponse
ApiResponse -->> AuthController: return ApiResponse instance
deactivate ApiResponse 
AuthController -->> AsyncHandler: return ApiResponse instance
deactivate AuthController
AsyncHandler --> Client: HTTP 200 Success
deactivate AsyncHandler
deactivate AuthRouter


@enduml