@startuml Forgot Password

actor Client

participant AuthController
participant RequestValidation
participant AuthService
participant UsersService
participant MailerService
participant StringUtil
participant UserOtpModel
participant UserModel

database MongoDB

' Step 1
    activate Client
    Client -> AuthController: POST /api/auth/forgot-password
    activate AuthController


' Step 2
group Validation Flow
    AuthController -> RequestValidation: validateSchema(ForgotPasswordDto)
    activate RequestValidation
    alt validation error
        RequestValidation --x RequestValidation: throw HttpException(400)
        RequestValidation --x AuthController: throw HttpException(400)
        AuthController -->> Client: HTTP 400 Bad Request
    end
    RequestValidation -->> AuthController: return valid data
    deactivate RequestValidation
end

' step 3
group Business Logic Flow
    AuthController -> UsersService: getUserByIdService(userId)
    activate UsersService

    UsersService -> UserModel: findOne(filters)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt select fail 
        MongoDB --x UserModel: throw Error
        UserModel --x UsersService: throw Error
        UsersService --x AuthController: throw Error
        AuthController -->> Client: HTTP 500 Internal Server Error

    else user not found
        MongoDB -->> UserModel: return null
        UserModel -->> UsersService: return null
        UsersService -->> AuthController: return null
        AuthController --x AuthController: throw(HttpException(404))
        AuthController -->> Client: HTTP 404 Not Found
    end

    MongoDB -->> UserModel: return user
    deactivate MongoDB
    UserModel -->> UsersService: return user
    deactivate UserModel
    UsersService -->> AuthController: return user
    deactivate UsersService
    AuthController -> AuthService: createResetPasswordTokenService(userId)
    activate AuthService
    AuthService -> Jsonwebtoken: sign(payload, secret, options)
    activate Jsonwebtoken
    Jsonwebtoken -->> AuthService: return token
    deactivate Jsonwebtoken
    AuthService -->> AuthController: return token
    deactivate AuthService
    AuthController -> AuthController: join()
    AuthController -> MailerService: sendResetPasswordRequestService(email, resetURL)
    activate MailerService
    MailerService -> MailerService: getEmailTemplateToString()
    MailerService -> MailerService: sendMail()

    alt send mail fail
        MailerService --x MailerService: throw error
        MailerService --x AuthController: throw error
        AuthController -->> Client: HTTP 500 Internal Server Error
    end

    MailerService -->> AuthController: return result
    deactivate MailerService
       
end   
break

AuthController --> Client: HTTP 200 Success
deactivate AuthController


@enduml