@startuml Search Product

actor Client

box "Application Layer"
participant ProductRouter 
participant ErrorMiddleware 
participant AsyncHandler 
end box

box "Authentication"
participant JwtAuthMiddleware 
participant CookieUtil
participant AuthService
participant jsonwebtoken
end box

box "Authorization"
participant UserService 
participant UserModel
end box

box "Validation"
participant RequestValidation
end box

box "Business Logic"
participant ProductsController
participant ModelDto
participant ApiResponse
participant ProductsService
participant QueryUtil
participant ProductModel
end box

database MongoDB

' Step 1
group Request Initialization
    Client -> ProductRouter: GET /api/products/get-products
    activate Client
    activate ProductRouter
    ProductRouter -> AsyncHandler: asyncHandler(getAllProductsController)
    activate AsyncHandler
end

break
break

' Step 2
group Authentication Flow
    AsyncHandler -> JwtAuthMiddleware: isAuthorizedAndHasPermission
    activate JwtAuthMiddleware

    JwtAuthMiddleware -> JwtAuthMiddleware: extract token
    alt token not provided
        JwtAuthMiddleware -> CookieUtil: clearSession(res)
        activate CookieUtil
        CookieUtil -->> JwtAuthMiddleware: return void
        deactivate CookieUtil
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end 

    JwtAuthMiddleware -> AuthService: verifyTokenService(token)
    activate AuthService
    AuthService -> jsonwebtoken: verify(token, SECRET)
    activate jsonwebtoken
    alt token invalid
        jsonwebtoken --x AuthService: throw Error
        AuthService -->> JwtAuthMiddleware: catch Error and return null
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end

    jsonwebtoken -->> AuthService: return data decoded
    deactivate jsonwebtoken
    AuthService -->> JwtAuthMiddleware: return data decoded
    deactivate AuthService
    JwtAuthMiddleware -> UserService: getUserByIdService(decoded.id)
    activate UserService
    UserService -> UserModel: findOne(filters)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt user not found
        MongoDB -->> UserModel: return null
        UserModel -->> UserService: return null
        UserService -->> JwtAuthMiddleware: return null
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return user
    deactivate MongoDB
    UserModel -->> UserService: return user
    deactivate UserModel
    UserService -->> JwtAuthMiddleware: return user
    deactivate UserService

    alt unverified account
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(403))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 403 Forbidden
        deactivate ErrorMiddleware
    end
end

break
break

' Step 3
group Authorization Flow
    JwtAuthMiddleware -> UserService: checkUserHasPermissionService(userId, method, endpoint)
    activate UserService
    UserService -> UserModel: findById(id).populate(role).populate(permissions)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt User doesn't have permissions 
        MongoDB -->> UserModel: return empty permissions
        UserModel -->> UserService: return empty permissions
        UserService -->> JwtAuthMiddleware: return false
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 403 Forbidden
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return permissions
    deactivate MongoDB
    UserModel -->> UserService: return permissions
    deactivate UserModel
    UserService -->> JwtAuthMiddleware: return true
    deactivate UserService
end

break
break

' Step 4
group Validation Flow
    JwtAuthMiddleware -> RequestValidation: validateQuery(GetListProductDto)
    activate RequestValidation
        alt validation error
        RequestValidation ->> RequestValidation: next(HttpException(400))
        RequestValidation ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 400 Bad Request
        deactivate ErrorMiddleware
    end
end

break
break


' Step 5
group Business Logic Flow
    RequestValidation -> ProductsController: getAllProductsController
    deactivate RequestValidation
    activate ProductsController
    ProductsController -> ProductsService: countAllProductsService(filterOptions)
    activate ProductsService
    ProductsService -> ProductModel: countDocuments(filters)
    activate ProductModel
    ProductModel -> MongoDB: query count 
    activate MongoDB

    alt count false
        MongoDB --x ProductModel:throw Error
        ProductModel --x ProductsService:throw Error
        ProductsService --x ProductsController: throw Error
        ProductsController --x AsyncHandler: catch Error and next(Error)
        AsyncHandler ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500  Server Error
        deactivate ErrorMiddleware
    end

    MongoDB -->> ProductModel: return count
    deactivate MongoDB
    ProductModel -->> ProductsService: return count
    deactivate ProductModel
    ProductsService -->> ProductsController: return count
    deactivate ProductsService
    ProductsController -> ProductsService: getAllProductsService(filters, page, limit, sortBy, sortOrder)
    activate ProductsService
    ProductsService -> ProductModel: find(filters)
    activate ProductModel
    ProductModel -> MongoDB: query select
    activate MongoDB

    alt select fail
        MongoDB --x ProductModel: throw Error
        ProductModel --x ProductsService: throw Error
        ProductsService --x ProductsController: throw Error
        ProductsController --x AsyncHandler: catch Error and next(Error)
        AsyncHandler ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500  Server Error
        deactivate ErrorMiddleware
    end

    MongoDB -->> ProductModel: return products
    deactivate MongoDB
    ProductModel -->> ProductsService: return products
    deactivate ProductModele
    ProductsService -->> ProductsController: return products
    deactivate ProductsService
    
end

group Transform data response
    ProductsController -> ModelDto: newList(ProductDto, products)
    activate ModelDto
    ModelDto -->> ProductsController: return ProductDto instance
    deactivate ModelDto

    ProductsController -> ApiResponse: success(TotalCount, ProductDto, success message)
    activate ApiResponse
    ApiResponse -->> ProductsController: return ApiResponse instance
    deactivate ApiResponse 
end

ProductsController -->> AsyncHandler: return ApiResponse instance
deactivate ProductsController
AsyncHandler --> Client: HTTP 200 Success
deactivate AsyncHandler
deactivate ProductRouter

@enduml