@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC10.5: Change Password

|User|
start
note left
    User is logged in  
    In UC10.1
end note

|User|
:Click to change password button;

|System|
:Display a form modal;

|User|
repeat 
    repeat
        :Enter the required details;
        :Submit the form;

        |System|
        :Validate the input;
        backward :Show detailed error;
    repeat while(Is valid?) is(no) not(yes)

    :Verify the current password;
    backward :Display an error message;
repeat while(Is correct password?) is(no) not(yes)

:Update the new password in the database;
:Display a success message;
stop

@enduml
