@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC12.4: View role details

|User|
start
note left
    User is logged in  
    User must have permission
    In UC12.1
end note

|User|
:Select a role from the list and 
clicks to option “View details”;

|System|
:Redirect the user to the details page;
:Check the role exists;

if(Is exist role?) then(yes)    
    :Display the details of the selected role;
    stop
else(no)
    :Display error message "Not found";
    stop
endif


@enduml
