@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC13.7: Reset user password

|User|
start
note left
    User is logged in  
    User must have permission
    In UC13.4
end note


|User|
:Click to reset password button;

|System|
:Display a confirmation prompt;

|User|
if(User clicks "Change") then(yes)
else(no)
    stop
endif

|System|
:Check the user exists;
if(Exist user?) then(yes)
    :Generate new password;
    :Update user password in the database;
    :Send the new password to the user's email;
    :Display success message;
    stop
else(no)
    :Display error message;
    stop
endif



@enduml
