@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC15.1: View product list

|User|
start
note left
    User is logged in  
    User must have permission
end note

|User|
:Navigate to the "Products management" section;

|System|
:Retrieve the list of products from the database;
:Check the results;

if(Results available?) then(yes)
    :Display the list of products;
else(no)
    :Display a message "No results found";
endif

stop

@enduml
