@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC16.4: View order details

|User|
start
note left
    User is logged in  
    User must have permission
    In UC16.1
end note

|User|
:Select a order from the list and 
clicks to option “View details”;

|System|
:Redirect the order to the details page;
:Check the order exists;

if(Order exists?) then(yes)    
    :Display the details of the selected order;
    stop
else(no)
    :Display error message "Not found";
    stop
endif


@enduml
