@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC15.6: Remove category

|User|
start
note left
    User is logged in  
    User must have permission
end note


|User|
:Click to remove button in 
view category details page;

|System|
:Display a confirmation prompt;

|User|
if(User clicks "Remove") then(yes)
else(no)
    stop
endif

|System|
:Check the category exists;
if(Exist category?) then(yes)
    :Update the category as removed in the database;
        :Display success message;
        stop
        note right
            Go to UC15.1
        end note
else(no)
    :Display error message;
    stop
endif

@enduml
