@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC16.1: View customer list

|User|
start
note left
    User is logged in  
    User must have permission
end note

|User|
:Navigate to the "Customer management" section;

|System|
:Retrieve the list of Customer from the database;
:Check the results;

if(Results available?) then(yes)
    :Display the list of Customer;
else(no)
    :Display a message "No results found";
endif

stop

@enduml
