@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC18.6: Remove customer

|User|
start
note left
    User is logged in  
    User must have permission
    In UC18.4
end note


|User|
:Click to remove button in 
view customer details page;

|System|
:Display a confirmation prompt;

|User|
if(User clicks "Remove") then(yes)
else(no)
    stop
endif

|System|
:Check the customer exists;
if(Exist customer?) then(yes)
    :Check customer have any order;
    if(Have order?) then(yes)
        :Display error message;
        stop
    else(no)
        :Update the customer as removed in the database;
        :Display success message;
        stop
        note right
            Go to UC18.1
        end note
    endif
else(no)
    :Display error message;
    stop
endif

@enduml
