@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC18.4: View customer details

|User|
start
note left
    User is logged in  
    User must have permission
    In UC18.1
end note

|User|
:Select a customer from the list and 
clicks to option “View details”;

|System|
:Redirect the customer to the details page;
:Check the customer exists;

if(Customer exists?) then(yes)    
    :Display the details of the selected customer;
    stop
else(no)
    :Display error message "Not found";
    stop
endif


@enduml
