@startuml

skinparam ActivityBackgroundColor LightYellow
skinparam ActivityBorderColor DarkOrange
skinparam ArrowColor Maroon

title UC8: Forgot password

|User|
start
note left
    User is not logged in
end note

|User|
:Navigate to the forgot password page;

|System|
:Display a forgot password form;

repeat
    repeat 
        repeat
            |User|
            :Enter email;
            :Submit the form;

            |System|
            :Validate the input;

            backward :Show detailed error;
        repeat while(Is valid?) is (no) not(yes)
    
        :Check account exist with the email provided;
        backward :Display error message;
    repeat while(Is exist?) is (no) not(yes)

    :Check the time limit;
    backward :Display error message;
repeat while(Request limit?) is (yes) not(no)

|System|
:Create a password reset token and save it in the database;
:Send a reset password link to the user's email;

|User|
:Check email and click to the reset password link;

|System|
:Redirect user to the reset password page;
:Display a reset password form;

repeat 
    |User|
    :Enter a new password and confirm password;
    :Submit the reset password form;

    |System|
    :Validate the new password;

    backward :Show detailed error;
repeat while(Is valid password?) is(no) not(yes)

:Check the reset password token existence
by the token and expiration time;
if(Is exist token?) then(yes)
    :Update the user's password in the database;
    :Display a success message;
    :Redirect user to the login page;
else(no)
    :Display error message;
    :Redirect user to the forgot password page;
endif

stop

@enduml
