@startuml List Cart

actor Client

participant CartsController
participant RequestValidation
participant CartsService

database MongoDB
database RedisClient

' Step 1
    activate Client
    Client -> CartsController: GET /api/carts/get-cart
    activate CartsController


' Step 4
group Validation Flow
    CartsController -> RequestValidation: validateSchema(GetListCustomerDto)
    activate RequestValidation
    alt validation error
        RequestValidation --x RequestValidation: throw HttpException(400)
        RequestValidation --x CartsController: throw HttpException(400)
        CartsController -->> Client: HTTP 400 Bad Request
    end
    RequestValidation -->> CartsController: return valid data
    deactivate RequestValidation
end

' Step 5
group Business Logic Flow
    CartsController -> CartsService: getCartService(id)
    activate CartsService
    CartsService -> RedisClient: hGetAll()
    activate RedisClient
    RedisClient -->> CartsService: return carts 
    deactivate RedisClient
    CartsService -->> CartsController: return carts
    deactivate CartsService
    

end
CartsController --> Client: HTTP 200 Success
deactivate CartsController

@enduml