@startuml Remove Item in Cart

actor Client

participant CartsController
participant ApiResponse
participant CartsService

database MongoDB
database RedisClient

' Step 1
    activate Client
    Client -> CartsController: GET /api/carts/remove-item/:productVariantId
    activate CartsController


' Step 4
group Business Logic Flow
    CartsController -> CartsService: removeFromCartService(id, productVariantId)
    activate CartsService
    CartsService -> RedisClient: hDel()
    activate RedisClient
    RedisClient -->> CartsService: return carts 
    deactivate RedisClient
    CartsService -->> CartsController: return carts
    deactivate CartsService
    
end


CartsController --> Client: HTTP 200 Success
deactivate CartsController

@enduml