@startuml Create User

actor Client
participant UsersController
participant ModelDto
participant RequestValidation
participant UsersService
participant UserModel
database MongoDB

activate Client
Client -> UsersController: POST /api/users/create-user
activate UsersController

group Validation Flow
    UsersController -> RequestValidation: validateSchema(CreateUserDto)
    activate RequestValidation
    
    alt validation error
        RequestValidation --x RequestValidation: throw HttpException(400)
        RequestValidation --x UsersController: throw HttpException(400)
        UsersController -->> Client: HTTP 400 Bad Request
    end

    RequestValidation -> UsersController: return valid data
    deactivate RequestValidation
end

group Business Logic Flow
    UsersController -> UsersService: checkExistEmailService(email)
    activate UsersService
    UsersService -> UserModel: findOne({ email })
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt User email exists
        MongoDB -->> UserModel: return user
        UserModel -->> UsersService: return user
        UsersService -->> UsersController: return true
        UsersController --x UsersController: throw HttpException(409)
        UsersController -->> Client: HTTP 409 Conflict
    end

    MongoDB -->> UserModel: return null
    deactivate MongoDB
    UserModel -->> UsersService: return null
    deactivate UserModel
    UsersService -->> UsersController: return false
    deactivate UsersService

    UsersController -> UsersService: createUserService(data)
    activate UsersService
    UsersService -> UserModel: create(data)
    activate UserModel
    UserModel -> MongoDB: query insert
    activate MongoDB

    alt Create fail
        MongoDB --x UserModel: throw Error
        UserModel --x UsersService: throw Error
        UsersService --x UsersController: throw Error
        UsersController -->> Client: HTTP 500 Server Error
    end

    MongoDB -->> UserModel: return user
    deactivate MongoDB
    UserModel -->> UsersService: return user
    deactivate UserModel
    UsersService -->> UsersController: return user
    deactivate UsersService
end

group Transform data
    UsersController -> ModelDto: new(UserDto)
    activate ModelDto
    ModelDto -> UsersController: return userDto
    deactivate ModelDto

    UsersController --> Client: HTTP 201 Created
    deactivate UsersController
end

deactivate Client

@enduml