@startuml View list Provinces

actor Client

participant DivisionsController
participant ModelDto
participant GhnService
participant GhnAPI 

database MongoDB

' Step 1
    activate Client
    Client -> DivisionsController: GET /api/divisions/get-provinces
    activate DivisionsController

break
break

' step 2
group Business Logic Flow
    DivisionsController -> GhnService: getAllProvincesService()
    activate GhnService
    GhnService -> GhnAPI: GET /master-data/province
    activate GhnAPI

    alt get fail
        GhnAPI -->> GhnService: return null
        GhnService -->> DivisionsController: return null
        DivisionsController --x DivisionsController: throw(HttpException(404))
        DivisionsController -->> Client: HTTP 404 Not Found
    end

    GhnAPI -->> GhnService: return province
    deactivate GhnAPI
    GhnService -->> DivisionsController: return province   
    deactivate GhnService


    

end
break
break

group Transform data response
    DivisionsController -> ModelDto: newList(ProvinceDto)
    activate ModelDto
    ModelDto -->> DivisionsController: return ProvinceDto 
    deactivate ModelDto
    
    DivisionsController --> Client: HTTP 200 Success
    deactivate DivisionsController

end



@enduml