@startuml
actor       User       
boundary    RegisterPage 
participant RequestValidation
participant AsyncHandler
boundary    UserController  
control     UserService
entity      UserModel     
database    Database 

activate User
User -> RegisterPage : Access to register page
activate RegisterPage

RegisterPage -> User: Display a register form
User -> RegisterPage : Enter input
User -> RegisterPage : Submits register form

RegisterPage -> RequestValidation: Validates request
activate RequestValidation

alt Valid data
    RequestValidation -> UserController : Send body
    activate UserController

    UserController -> UserService : Check exist email (email)
    activate UserService

    UserService -> UserModel: Find user (email)
    activate UserModel

    UserModel -> Database : Find user (email)
    activate Database

    alt Email does not exist
        Database -> UserModel: Return null

        UserModel -> UserService: Return null

        UserService -> UserController: Return null

        UserController -> UserService: Create user (body)

        UserService -> UserModel: Create user (body)

        UserModel -> Database: Create user (body)

        alt Create success
            Database -> UserModel: Return user document
        else Create failed
            Database -> UserModel: Throw error

            UserModel -> UserService: Throw error

            UserService -> UserController: Throw error
        end

    else Email already exists
        Database -> UserModel: Return user document
        deactivate Database

        UserModel -> UserService: Return user document
        deactivate UserModel

        UserService -> UserController: Return user document
        deactivate UserService

        UserController -> RegisterPage: Response error (409)
        deactivate UserController

        RegisterPage -> User: Display error message
    end
else Invalid data
    RequestValidation -> RegisterPage : Response error (400)
    deactivate RequestValidation

    RegisterPage -> User: Display detailed error
end

deactivate RegisterPage

@enduml
