@startuml View List Categories

actor Client

box "Application Layer"
participant CategoriesRouter 
participant ErrorMiddleware 
participant AsyncHandler 
end box

box "Authentication"
participant JwtAuthMiddleware 
participant CookieUtil
participant AuthService
participant jsonwebtoken
end box

box "Authorization"
participant UserService 
participant UserModel
end box

box "Validation"
participant RequestValidation
end box

box "Business Logic"
participant CategoriesController
participant ModelDto
participant ApiResponse
participant CategoriesService
participant QueryUtil
participant CategoryModel
end box

database MongoDB

' Step 1
group Request Initialization
    Client -> CategoriesRouter: GET /api/categories/get-categories
    activate Client
    activate CategoriesRouter
    CategoriesRouter -> AsyncHandler: asyncHandler(getAllCategoriesController)
    activate AsyncHandler
end

break
break

' Step 2
group Authentication Flow
    AsyncHandler -> JwtAuthMiddleware: isAuthorized
    activate JwtAuthMiddleware

    JwtAuthMiddleware -> JwtAuthMiddleware: extract token
    alt token not provided
        JwtAuthMiddleware -> CookieUtil: clearSession(res)
        activate CookieUtil
        CookieUtil -->> JwtAuthMiddleware: return void
        deactivate CookieUtil
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end 

    JwtAuthMiddleware -> AuthService: verifyTokenService(token)
    activate AuthService
    AuthService -> jsonwebtoken: verify(token, SECRET)
    activate jsonwebtoken
    alt token invalid
        jsonwebtoken --x AuthService: throw Error
        AuthService -->> JwtAuthMiddleware: catch Error and return null
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end

    jsonwebtoken -->> AuthService: return data decoded
    deactivate jsonwebtoken
    AuthService -->> JwtAuthMiddleware: return data decoded
    deactivate AuthService
    JwtAuthMiddleware -> UserService: getUserByIdService(decoded.id)
    activate UserService
    UserService -> UserModel: findOne(filters)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt user not found
        MongoDB -->> UserModel: return null
        UserModel -->> UserService: return null
        UserService -->> JwtAuthMiddleware: return null
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(401))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 401 Unauthorized
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return user
    deactivate MongoDB
    UserModel -->> UserService: return user
    deactivate UserModel
    UserService -->> JwtAuthMiddleware: return user
    deactivate UserService

    alt unverified account
        JwtAuthMiddleware ->> JwtAuthMiddleware: next(HttpException(403))
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 403 Forbidden
        deactivate ErrorMiddleware
    end
end

break
break

' Step 3
group Authorization Flow
    JwtAuthMiddleware -> UserService: checkUserHasPermissionService(userId, method, endpoint)
    activate UserService
    UserService -> UserModel: findById(id).populate(role).populate(permissions)
    activate UserModel
    UserModel -> MongoDB: query select
    activate MongoDB

    alt User doesn't have permissions 
        MongoDB -->> UserModel: return empty permissions
        UserModel -->> UserService: return empty permissions
        UserService -->> JwtAuthMiddleware: return false
        JwtAuthMiddleware ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 403 Forbidden
        deactivate ErrorMiddleware
    end

    MongoDB -->> UserModel: return permissions
    deactivate MongoDB
    UserModel -->> UserService: return permissions
    deactivate UserModel
    UserService -->> JwtAuthMiddleware: return true
    deactivate UserService
end

break
break

' Step 4
group Validation Flow
    JwtAuthMiddleware -> RequestValidation: validateSchema(GetListCategoryDto)
    deactivate JwtAuthMiddleware
    activate RequestValidation
        alt validation error
        RequestValidation ->> RequestValidation: next(HttpException(400))
        RequestValidation ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 400 Bad Request
        deactivate ErrorMiddleware
    end
end

break
break


' Step 5
group Business Logic Flow
    RequestValidation -> CategoriesController: getAllCategoriesController
    deactivate RequestValidation
    activate CategoriesController
    CategoriesController -> CategoriesService: getAndCountCategoriesService(null, filters, skip, limit, sortBy, sortOrder)
    activate CategoriesService
    CategoriesService -> QueryUtil: extendQueryOptionsWithPagination(skip, limit)
    activate QueryUtil
    QueryUtil -->> CategoriesService: return Options
    deactivate QueryUtil
    CategoriesService -> QueryUtil: extendQueryOptionsWithSort(sortBy, sortOrder)
    activate QueryUtil
    QueryUtil -->> CategoriesService: return Options
    deactivate QueryUtil
    CategoriesService -> CategoryModel: aggregate(filters, options)
    activate CategoryModel
    CategoryModel -> MongoDB: query aggregate
    activate MongoDB

    alt aggregate fail
        MongoDB --x CategoryModel: throw Error
        CategoryModel --x CategoriesService: throw Error
        CategoriesService --x CategoriesController: throw Error
        CategoriesController --x AsyncHandler: catch Error and next(Error)
        AsyncHandler ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500 Internal Server Error
        deactivate ErrorMiddleware
    end

    MongoDB -->> CategoryModel: return list categories
    deactivate MongoDB
    CategoryModel -->> CategoriesService: return list categories
    deactivate CategoryModel
    CategoriesService -> CategoryModel: aggregate(filters, options)
    activate CategoryModel
    CategoryModel -> MongoDB: query aggregate
    activate MongoDB

    alt aggregate fail
        MongoDB --x CategoryModel: throw Error
        CategoryModel --x CategoriesService: throw Error
        CategoriesService --x CategoriesController: throw Error
        CategoriesController --x AsyncHandler: catch Error and next(Error)
        AsyncHandler ->> ErrorMiddleware: handleError(Error)
        activate ErrorMiddleware
        ErrorMiddleware -->> Client: HTTP 500 Internal Server Error
        deactivate ErrorMiddleware
    end

    MongoDB -->> CategoryModel: return totalCount
    deactivate MongoDB
    CategoryModel -->> CategoriesService: return totalCount
    deactivate CategoryModel
    CategoriesService -->> CategoriesController: return totalCount and list categories
    deactivate CategoriesService

end

group Transform data response
    CategoriesController -> ModelDto: newList(CategoryDto, categories)
    activate ModelDto
    ModelDto -->> CategoriesController: return CategoryDto instance
    deactivate ModelDto

    CategoriesController -> ApiResponse: success(TotalCount, CategoryDto, success message)
    activate ApiResponse
    ApiResponse -->> CategoriesController: return ApiResponse instance
    deactivate ApiResponse 
end

CategoriesController -->> AsyncHandler: return ApiResponse instance
deactivate CategoriesController
AsyncHandler --> Client: HTTP 200 Success
deactivate AsyncHandler
deactivate CategoriesRouter

@enduml