@startuml View Detail Category

actor Client


participant CategoriesController
participant ModelDto
participant RequestValidation
participant CategoriesService
participant CategoryModel

database MongoDB

' Step 1
    activate Client
    Client -> CategoriesController: GET /api/categories/get-category-by-id/:categoryId
    activate CategoriesController



' Step 4
group Validation Flow
    CategoriesController -> RequestValidation: validateSchema(createCategoryDto)
    activate RequestValidation
    alt validation error
        RequestValidation --x RequestValidation: throw HttpException(400)
        RequestValidation --x CategoriesController: throw HttpException(400)
        CategoriesController -->> Client: HTTP 400 Bad Request
    end
    RequestValidation -->> CategoriesController: return valid data
    deactivate RequestValidation
end

break
break


' Step 5
group Business Logic Flow
    CategoriesController -> CategoriesService: getCategoryByIdService(categoryId)
    activate CategoriesService

    CategoriesService -> CategoryModel: findOne(filters)
    activate CategoryModel
    CategoryModel -> MongoDB: query select
    activate MongoDB

    alt select fail 
        MongoDB --x CategoryModel: throw Error
        CategoryModel --x CategoriesService: throw Error
        CategoriesService --x CategoriesController: throw Error
        CategoriesController -->> Client: HTTP 500 Internal Server Error
    else category not found
        MongoDB -->> CategoryModel: return null
        CategoryModel -->> CategoriesService: return null
        CategoriesService -->> CategoriesController: return null
        CategoriesController --x CategoriesController: throw(HttpException(404))
        CategoriesController -->> Client: HTTP 404 Not Found
    end

    MongoDB -->> CategoryModel: return category
    deactivate MongoDB
    CategoryModel -->> CategoriesService: return category
    deactivate CategoryModel
    CategoriesService -->> CategoriesController: return category
    deactivate CategoriesService
end

group Transform data response
    CategoriesController -> ModelDto: new(CategoryDto)
    activate ModelDto
    ModelDto -->> CategoriesController: return CategoryDto 
    deactivate ModelDto
CategoriesController --> Client: HTTP 200 Success
deactivate CategoriesController
end



@enduml