@startuml View Detail Shipping Address

actor Client

participant ShippingAddressController
participant ModelDto
participant ShippingAddressService
participant ShippingAddressModel

database MongoDB

' Step 1
    activate Client
    Client -> ShippingAddressController: GET /api/shipping-address/get-shipping-address-by-id/:shippingAddressId
    activate ShippingAddressController

' Step 4
group Business Logic Flow
    ShippingAddressController -> ShippingAddressService: getShippingAddressByIdService(shippingAddressId)
    activate ShippingAddressService
    
    ShippingAddressService -> ShippingAddressModel: findOne(filters)
    activate ShippingAddressModel
    ShippingAddressModel -> MongoDB: query select
    activate MongoDB

    alt select fail
        MongoDB --x ShippingAddressModel: throw Error
        ShippingAddressModel --x ShippingAddressService: throw Error
        ShippingAddressService --x ShippingAddressController: throw Error
        ShippingAddressController -->> Client: HTTP 500 Internal Server Error
    else shippingAddress not found
        MongoDB -->> ShippingAddressModel: return null
        ShippingAddressModel -->> ShippingAddressService: return null
        ShippingAddressService -->> ShippingAddressController: return null
        ShippingAddressController --x ShippingAddressController: Throw(HttpException(404))
        ShippingAddressController -->> Client: HTTP 404 Not Found
    end

    MongoDB -->> ShippingAddressModel: return shippingAddress
    deactivate MongoDB
    ShippingAddressModel -->> ShippingAddressService: return shippingAddress
    deactivate ShippingAddressModel
    ShippingAddressService -->> ShippingAddressController: return shippingAddress
    deactivate ShippingAddressService


end

group Transform data response
    ShippingAddressController -> ModelDto: newList(ShippingAddressDto)
    activate ModelDto
    ModelDto -->> ShippingAddressController: return ShippingAddressDto 
    deactivate ModelDto

ShippingAddressController --> Client: HTTP 200 Success
deactivate ShippingAddressController
end

@enduml