/** @type {import('#src/models/permission.model')} */

import { PERMISSION_STATUS } from '#src/app/v1/permissions/permissions.constant';

const USERS_PERMISSIONS = [
  {
    name: 'Get users list',
    module: 'users',
    endpoint: '/api/v1/users/get-users',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Get user by id',
    module: 'users',
    endpoint: '/api/v1/users/get-user-by-id/:userId',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Create user',
    module: 'users',
    endpoint: '/api/v1/users/create-user',
    method: 'POST',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Update user by id',
    module: 'users',
    endpoint: '/api/v1/users/update-user-by-id/:userId',
    method: 'PUT',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Remove user by id',
    module: 'users',
    endpoint: '/api/v1/users/remove-user-by-id/:userId',
    method: 'DELETE',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
];

const ROLES_PERMISSIONS = [
  {
    name: 'Get roles list',
    module: 'roles',
    endpoint: '/api/v1/roles/get-roles',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Get role by id',
    module: 'roles',
    endpoint: '/api/v1/roles/get-role-by-id/:roleId',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Create role',
    module: 'roles',
    endpoint: '/api/v1/roles/create-role',
    method: 'POST',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Update role by id',
    module: 'roles',
    endpoint: '/api/v1/roles/update-role-by-id/:roleId',
    method: 'PUT',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Remove role by id',
    module: 'roles',
    endpoint: '/api/v1/roles/remove-role-by-id/:roleId',
    method: 'DELETE',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Activate role by id',
    module: 'roles',
    endpoint: '/api/v1/roles/activate-role-by-id/:roleId',
    method: 'PATCH',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Deactivate role by id',
    module: 'roles',
    endpoint: '/api/v1/roles/deactivate-role-by-id/:roleId',
    method: 'PATCH',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
];

const PERMISSIONS_PERMISSIONS = [
  {
    name: 'Get permissions list',
    module: 'permissions',
    endpoint: '/api/v1/permissions/get-permissions',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Get permission by id',
    module: 'permissions',
    endpoint: '/api/v1/permissions/get-permission-by-id/:permissionId',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Update permission by id',
    module: 'permissions',
    endpoint: '/api/v1/permissions/update-permission-by-id/:permissionId',
    method: 'PUT',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Activate permission by id',
    module: 'permissions',
    endpoint: '/api/v1/permissions/activate-permission-by-id/:permissionId',
    method: 'PATCH',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Deactivate permission by id',
    module: 'permissions',
    endpoint: '/api/v1/permissions/deactivate-permission-by-id/:permissionId',
    method: 'PATCH',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
];

const CATEGORIES_PERMISSIONS = [
  {
    name: 'Get categories list',
    module: 'categories',
    endpoint: '/api/v1/categories/get-categories',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Get category by id',
    module: 'categories',
    endpoint: '/api/v1/categories/get-category-by-id/:categoryId',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Create category',
    module: 'categories',
    endpoint: '/api/v1/categories/create-category',
    method: 'POST',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Update category by id',
    module: 'categories',
    endpoint: '/api/v1/categories/update-category-by-id/:categoryId',
    method: 'PUT',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Remove category by id',
    module: 'categories',
    endpoint: '/api/v1/categories/remove-category-by-id/:categoryId',
    method: 'DELETE',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Show category by id',
    module: 'categories',
    endpoint: '/api/v1/categories/show-category-by-id/:categoryId',
    method: 'PATCH',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Hide categories by id',
    module: 'categories',
    endpoint: '/api/v1/categories/hide-category-by-id/:categoryId',
    method: 'PATCH',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
];

const CUSTOMERS_PERMISSIONS = [
  {
    name: 'Get customers list',
    module: 'customers',
    endpoint: '/api/v1/customers/get-customers',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Get customer by id',
    module: 'customers',
    endpoint: '/api/v1/customers/get-customer-by-id/:customerId',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Create customer',
    module: 'customers',
    endpoint: '/api/v1/customers/create-customer',
    method: 'POST',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Update customer by id',
    module: 'customers',
    endpoint: '/api/v1/customers/update-customer-by-id/:customerId',
    method: 'PUT',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Remove customer by id',
    module: 'customers',
    endpoint: '/api/v1/customers/remove-customer-by-id/:customerId',
    method: 'DELETE',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
];

const VOUCHERS_PERMISSIONS = [
  {
    name: 'Get vouchers list',
    module: 'vouchers',
    endpoint: '/api/v1/vouchers/get-vouchers',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Get voucher by id',
    module: 'vouchers',
    endpoint: '/api/v1/vouchers/get-voucher-by-id/:voucherId',
    method: 'GET',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Create voucher',
    module: 'vouchers',
    endpoint: '/api/v1/vouchers/create-voucher',
    method: 'POST',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Update voucher by id',
    module: 'vouchers',
    endpoint: '/api/v1/vouchers/update-voucher-by-id/:voucherId',
    method: 'PUT',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
  {
    name: 'Remove voucher by id',
    module: 'vouchers',
    endpoint: '/api/v1/vouchers/remove-voucher-by-id/:voucherId',
    method: 'DELETE',
    isActive: true,
    status: PERMISSION_STATUS.ACTIVE,
  },
];

export const PERMISSIONS_LIST = [
  ...USERS_PERMISSIONS,
  ...ROLES_PERMISSIONS,
  ...PERMISSIONS_PERMISSIONS,
  ...CATEGORIES_PERMISSIONS,
  ...CUSTOMERS_PERMISSIONS,
  ...VOUCHERS_PERMISSIONS,
];
